manage temporary directory

diff --git a/pggb b/pggb
--- a/pggb
+++ b/pggb
@@ -281,34 +281,40 @@ prefix_seqwish="$prefix_paf".$(echo k$min_match_length-f$sparse_factor-B$transcl
 
 # Normalization
 block_id_min=$(echo "scale=4; $map_pct_id / 100.0" | bc)
-prefix_smoothed="$prefix_seqwish".$(echo h$n_haps-G$target_poa_length-j$max_path_jump-e$max_edge_jump-d$pad_max_depth-I$block_id_min-R$block_ratio_min-p$poa_params-O$poa_padding | sha256sum | head -c 7)
+prefix_smoothed="$prefix_seqwish".$(echo h$n_haps-G$target_poa_length-j$max_path_jump-e$max_edge_jump-d$pad_max_depth-I$block_id_min-R$block_ratio_min-p$poa_params-O$poa_padding | sha256sum | head -c 7).smooth
+prefix_smoothed_output="$prefix_smoothed"
 
 
 fmt="%C\n%Us user %Ss system %P cpu %es total %MKb max memory"
 timer=$(which time)
 
+
+# Directories
 if [[ "$output_dir" != "" ]]; then
 	if [ ! -e "$output_dir" ]; then
 		mkdir "$output_dir"
 	fi
+
 	prefix_paf="$output_dir"/$(basename "$prefix_paf")
-	prefix_seqwish="$output_dir"/$(basename "$prefix_seqwish")
-	prefix_smoothed="$output_dir"/$(basename "$prefix_smoothed")
+	prefix_smoothed_output="$output_dir"/$(basename "$prefix_smoothed")
 fi
 
 if [[ "$temp_dir" == "" ]]; then
   temp_dir=$output_dir
 fi
-
 if [[ "$temp_dir" != "" ]]; then
   if [ ! -e "$temp_dir" ]; then
     mkdir "$temp_dir"
   fi
+
+  prefix_seqwish="$temp_dir"/$(basename "$prefix_seqwish")
+  prefix_smoothed="$temp_dir"/$(basename "$prefix_smoothed")
 fi
 
+
 date=`date "+%m-%d-%Y_%H:%M:%S"`
-log_file="$prefix_smoothed".$date.log
-param_file="$prefix_smoothed".$date.params.yml
+log_file="$prefix_smoothed_output".$date.log
+param_file="$prefix_smoothed_output".$date.params.yml
 
 # write parameters to log_file:
 echo -e "Starting pggb on `date`\n" > "$log_file"
@@ -417,13 +423,13 @@ fi
 
 if [[ $consensus_spec != false ]]; then
     # for merging consensus (currently problematic) we should add "-M -J 1 -G 150" here
-    consensus_params="-C "$prefix_smoothed".cons,"$consensus_spec
+    consensus_params="-C ${prefix_smoothed_output}.cons,$consensus_spec"
 else
     consensus_params="-V"
 fi
 
 if [[ $write_maf != false ]]; then
-    maf_params="-m "$prefix_smoothed".smooth.maf"
+    maf_params="-m ${prefix_smoothed_output}.maf"
 fi
 
 # how many times will we smooth?
@@ -443,10 +449,10 @@ for i in $(seq 1 $smooth_iterations);
 do
     input_gfa="$prefix_seqwish".seqwish.gfa
     if [[ $i != 1 ]]; then
-        input_gfa="$prefix_smoothed".smooth.$(echo $i - 1 | bc).gfa
+        input_gfa="$prefix_smoothed".$(echo $i - 1 | bc).gfa
     fi
-    if [[ $i != $smooth_iterations ]]; then
-        if [[ ! -s $prefix_smoothed.smooth.$i.gfa || $resume == false ]]; then
+    if [[ $i != "$smooth_iterations" ]]; then
+        if [[ ! -s $prefix_smoothed.$i.gfa || $resume == false ]]; then
             poa_length=$(echo $target_poa_length | cut -f $i -d, )
             $timer -f "$fmt" smoothxg \
                    -t $threads \
@@ -466,11 +472,11 @@ do
                    -Y $(echo "$pad_max_depth * $n_haps" | bc) \
                    -d 0 -D 0 \
                    -V \
-                   -o "$prefix_smoothed".smooth.$i.gfa \
+                   -o "$prefix_smoothed".$i.gfa \
                    2> >(tee -a "$log_file")
         fi
     else
-        if [[ ! -s $prefix_smoothed.smooth.gfa || $resume == false ]]; then
+        if [[ ! -s $prefix_smoothed.gfa || $resume == false ]]; then
             poa_length=$(echo $target_poa_length | cut -f $i -d, )
             $timer -f "$fmt" smoothxg \
                    -t $threads \
@@ -492,7 +498,7 @@ do
                    $maf_params \
                    -Q $consensus_prefix \
                    $consensus_params \
-                   -o "$prefix_smoothed".smooth.gfa \
+                   -o "$prefix_smoothed".gfa \
                    2> >(tee -a "$log_file")
         fi
     fi
@@ -503,17 +509,16 @@ if [[ "$temp_dir" != "" ]]; then
   odgi_temp_dir="--temp-dir $temp_dir"
 fi
 
-prefix_final_graph="$prefix_smoothed".smooth.final
 if [[ $normalize == true ]];
 then
     # Remove redundancy and sort
-    ( $timer -f "$fmt" gfaffix "$prefix_smoothed".smooth.gfa -o "$prefix_final_graph".gfa | $timer -f "$fmt" pigz >"$prefix_final_graph".affixes.tsv.gz ) 2> >(tee -a "$log_file")
-    ( $timer -f "$fmt" odgi build -t $threads -P -g "$prefix_final_graph".gfa -o - -O \
-        | $timer -f "$fmt" odgi sort -P -p Ygs $odgi_temp_dir -t $threads -i - -o "$prefix_final_graph".og ) 2> >(tee -a "$log_file")
-    ( $timer -f "$fmt" odgi view -i "$prefix_final_graph".og -g >"$prefix_final_graph".gfa ) 2> >(tee -a "$log_file")
+    ( $timer -f "$fmt" gfaffix "$prefix_smoothed".gfa -o "$prefix_smoothed_output".final.gfa | $timer -f "$fmt" pigz > "$prefix_smoothed_output".final.affixes.tsv.gz ) 2> >(tee -a "$log_file")
+    ( $timer -f "$fmt" odgi build -t $threads -P -g "$prefix_smoothed_output".final.gfa -o - -O \
+        | $timer -f "$fmt" odgi sort -P -p Ygs $odgi_temp_dir -t $threads -i - -o "$prefix_smoothed_output".final.og ) 2> >(tee -a "$log_file")
+    ( $timer -f "$fmt" odgi view -i "$prefix_smoothed_output".final.og -g > "$prefix_smoothed_output".final.gfa ) 2> >(tee -a "$log_file")
 else
-    mv "$prefix_smoothed".smooth.gfa "$prefix_final_graph".gfa
-    $timer -f "$fmt" odgi build -t $threads -P -g "$prefix_final_graph".gfa -o "$prefix_final_graph".og 2> >(tee -a "$log_file")
+    mv "$prefix_smoothed".gfa "$prefix_smoothed_output".final.gfa
+    $timer -f "$fmt" odgi build -t $threads -P -g "$prefix_smoothed_output".final.gfa -o "$prefix_smoothed_output".final.og 2> >(tee -a "$log_file")
 fi
 
 if [[ $multiqc == true ]];
@@ -525,9 +530,9 @@ if [[ $do_stats == true ]];
 then
     $timer -f "$fmt" odgi build -t $threads -P -g "$prefix_seqwish".seqwish.gfa -o "$prefix_seqwish".seqwish.og 2> >(tee -a "$log_file")
     odgi stats -i "$prefix_seqwish".seqwish.og -m > "$prefix_seqwish".seqwish.og.stats.yaml 2>&1 | tee -a "$log_file"
-    odgi stats -i "$prefix_final_graph".og -m  > "$prefix_final_graph".og.stats.yaml 2>&1 | tee -a "$log_file"
+    odgi stats -i "$prefix_smoothed_output".final.og -m  > "$prefix_smoothed_output".final.og.stats.yaml 2>&1 | tee -a "$log_file"
     if [[ $consensus_spec != false ]]; then
-        for consensus_graph in "$prefix_smoothed"*.cons*.gfa; do
+        for consensus_graph in "$prefix_smoothed_output"*.cons*.gfa; do
             odgi build -t $threads -P -g "$consensus_graph" -o "$consensus_graph".og 2> >(tee -a "$log_file")
             odgi stats -i "$consensus_graph".og -m >"$consensus_graph".og.stats.yaml 2>&1 | tee -a "$log_file"
         done
@@ -537,20 +542,20 @@ fi
 if [[ $do_viz == true ]];
 then
     # big problem: this assumes that there is no "Consensus_" in the input sequences
-    $timer -f "$fmt" odgi viz -i "$prefix_final_graph".og \
-                    -o "$prefix_final_graph".og.viz_multiqc.png \
+    $timer -f "$fmt" odgi viz -i "$prefix_smoothed_output".final.og \
+                    -o "$prefix_smoothed_output".final.og.viz_multiqc.png \
                     -x 1500 -y 500 -a 10 -I $consensus_prefix \
                     2> >(tee -a "$log_file")
-    $timer -f "$fmt" odgi viz -i "$prefix_final_graph".og \
-                    -o "$prefix_final_graph".og.viz_pos_multiqc.png \
+    $timer -f "$fmt" odgi viz -i "$prefix_smoothed_output".final.og \
+                    -o "$prefix_smoothed_output".final.og.viz_pos_multiqc.png \
                     -x 1500 -y 500 -a 10 -u -d -I $consensus_prefix \
                     2> >(tee -a "$log_file")
-    $timer -f "$fmt" odgi viz -i "$prefix_final_graph".og \
-                    -o "$prefix_final_graph".og.viz_depth_multiqc.png \
+    $timer -f "$fmt" odgi viz -i "$prefix_smoothed_output".final.og \
+                    -o "$prefix_smoothed_output".final.og.viz_depth_multiqc.png \
                     -x 1500 -y 500 -a 10 -m -I $consensus_prefix \
                     2> >(tee -a "$log_file")
-    $timer -f "$fmt" odgi viz -i "$prefix_final_graph".og \
-                    -o "$prefix_final_graph".og.viz_inv_multiqc.png \
+    $timer -f "$fmt" odgi viz -i "$prefix_smoothed_output".final.og \
+                    -o "$prefix_smoothed_output".final.og.viz_inv_multiqc.png \
                     -x 1500 -y 500 -a 10 -z -I $consensus_prefix \
                     2> >(tee -a "$log_file")
 fi
@@ -558,27 +563,27 @@ fi
 if [[ $do_layout == true ]];
 then
     # the 2D layout is "smoother" when we chop the nodes of the graph to a fixed maximum length
-    #$timer -f "$fmt" odgi chop -i "$prefix_final_graph".og -c 100 -o ""$prefix_final_graph".chop.og \
+    #$timer -f "$fmt" odgi chop -i "$prefix_smoothed_output".final.og -c 100 -o ""$prefix_smoothed_output".final.chop.og \
     #    2> >(tee -a "$log_file")
 
     # adding `-N g` to this call can help when rendering large, complex graphs that aren't globally linear
-    $timer -f "$fmt" odgi layout -i "$prefix_final_graph".og \
-                       -o "$prefix_final_graph".og.lay \
-                       -T "$prefix_final_graph".og.lay.tsv \
+    $timer -f "$fmt" odgi layout -i "$prefix_smoothed_output".final.og \
+                       -o "$prefix_smoothed_output".final.og.lay \
+                       -T "$prefix_smoothed_output".final.og.lay.tsv \
                        -t $threads $odgi_temp_dir -P \
                        2> >(tee -a "$log_file")
 
     # this can be configured to draw the graph in different ways, based on the same layout
     # here we draw in default mode
-    $timer -f "$fmt" odgi draw -i "$prefix_final_graph".og \
-                     -c "$prefix_final_graph".og.lay \
-                     -p "$prefix_final_graph".og.lay.draw.png \
+    $timer -f "$fmt" odgi draw -i "$prefix_smoothed_output".final.og \
+                     -c "$prefix_smoothed_output".final.og.lay \
+                     -p "$prefix_smoothed_output".final.og.lay.draw.png \
                      -H 1000 \
                      2> >(tee -a "$log_file")
     # this attempts to add paths
-    $timer -f "$fmt" odgi draw -i "$prefix_final_graph".og \
-                     -c "$prefix_final_graph".og.lay \
-                     -p "$prefix_final_graph".og.lay.draw_multiqc.png \
+    $timer -f "$fmt" odgi draw -i "$prefix_smoothed_output".final.og \
+                     -c "$prefix_smoothed_output".final.og.lay \
+                     -p "$prefix_smoothed_output".final.og.lay.draw_multiqc.png \
                      -C -w 20 \
                      -H 1000 \
                      2> >(tee -a "$log_file")
@@ -591,9 +596,9 @@ then
         ref=$(echo "$s" | cut -f 1 -d: )
         delim=$(echo "$s" | cut -f 2 -d: )
         echo "[vg::deconstruct] making VCF with reference=$ref and delim=$delim"
-        vcf="$prefix_final_graph".$(echo $ref | tr '/|' '_').vcf
+        vcf="$prefix_smoothed_output".final.$(echo $ref | tr '/|' '_').vcf
         ( TEMPDIR=$(pwd) $timer -f "$fmt" vg deconstruct -P $ref \
-                 -H $delim -e -a -t $threads "$prefix_final_graph".gfa >"$vcf" ) 2> >(tee -a "$log_file")
+                 -H $delim -e -a -t $threads "$prefix_smoothed_output".final.gfa >"$vcf" ) 2> >(tee -a "$log_file")
         bcftools stats "$vcf" > "$vcf".stats
     done
 fi
@@ -669,14 +674,30 @@ then
     fi
 fi
 
-if [[ $keep_intermediate_files != true ]];
+if [[ $keep_intermediate_files == true ]];
 then
-  rm -f "$prefix_seqwish".seqwish.{gfa,og}
-  rm -f "$prefix_smoothed".smooth.[0-9]*.{gfa,og}
+  # `|| true` to avoid `mv` fail if there are missing files to move
+  mv -f "$prefix_seqwish".seqwish.{gfa,og} "$output_dir" 2> /dev/null || true
+  mv -f "$prefix_seqwish".*.prep.gfa "$output_dir" 2> /dev/null || true
+  mv -f "$prefix_smoothed".[0-9]*.{gfa,og} "$output_dir" 2> /dev/null || true
 
   if [[ $normalize == true ]];
   then
-    rm -f "$prefix_smoothed".smooth.{gfa,og}
+    mv -f "$prefix_smoothed".{gfa,og} "$output_dir" 2> /dev/null || true
+  fi
+
+  # Since the files have just been moved
+  if [[ "$output_dir" != "" ]]; then
+    prefix_seqwish="$output_dir"/$(basename "$prefix_seqwish")
+    prefix_smoothed="$output_dir"/$(basename "$prefix_smoothed")
+  fi
+else
+  rm -f "$prefix_seqwish".seqwish.{gfa,og}
+  rm -f "$prefix_smoothed".[0-9]*.{gfa,og}
+
+  if [[ $normalize == true ]];
+  then
+    rm -f "$prefix_smoothed".{gfa,og}
   fi
 fi
 
@@ -694,6 +715,6 @@ then
       ls "$prefix_seqwish"*.vcf | while read f; do bgzip $f -f -@ $threads; done
     fi
     if [[ $do_layout == true ]]; then
-        pigz -f -q -p $threads "$prefix_final_graph".og.lay.tsv -v
+        pigz -f -q -p $threads "$prefix_smoothed_output".final.og.lay.tsv -v
     fi
 fi
